language: php

php:
  - 5.5
  - 5.6

notifications:
  email: false

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - travis_retry composer self-update
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

script:
  - phpunit testfolder/output.php
  - phpunit --coverage-clover coverage.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash) 
 
deploy:
  provider: s3
  access_key_id: AKIAJMPXKY3TCIDIEGTA 
  secret_access_key:
    secure: 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
  bucket: cps847group6
  local-dir: 
  region: us-east-2
