language: php

php:
  - 5.5
  - 5.6
  - 7.0

notifications:
  email: false

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
 
script:
  - phpunit testfolder/test.phpt
