language: python
  python:
    - "2.7"
    - "3.6"
    
  install: 
    - pip install codecov
    - pip install coverage
    
  script:
    - python -m unittest discover -v ./ci_play/
    - coverage run ./ci_play/test.py
    
    after_success: 
    - codecov --token=9bfd390b-4801-4719-9501-b6750a7f2df1 
