language: generic

php: 
  - 5.5
  - 5.6
  - 7.0

install: skip
  
 before_script: 
  - gem install rake
  
 script: 
  - bundle exec thor build
  - test_folder/test.phpt 
  
 deploy:
  provider: s3
  access_key_id: "AKIAJQPDITG2T6DRFCDA"
  secret_access_key: "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"
  bucket: "S3 Bucket"
