language: php

php:
  - 5.5
  - 5.6

notifications:
  email: false

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - travis_retry composer self-update


script:
  - phpunit testfolder/output.php
  - phpunit --coverage-clover coverage.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash) 
 
deploy:
  provider: s3
  access_key_id: AKIAJIV26GAWMWFHNI2A 
  secret_access_key: 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
  bucket: cps847group6
  local-dir: 
  region: us-east-2
