language: php

php:
  - 5.5
  - 5.6
  - 7.0

notifications:
  email: false

before_script:
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
 
script:
  - phpunit 
