language: php

php:
  - 5.5
  - 5.6

notifications:
  email: false

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev


script:
  - phpunit testfolder/output.php
  - phpunit --coverage-clover=coverage.xml
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ffc95a1a-2b57-48c5-8a71-c7bb784196a9
 
deploy:
  provider: s3
  access_key_id: AKIAJMPXKY3TCIDIEGTA 
  secret_access_key:
    secure: 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
  bucket: cps847group6
  local-dir: 
  region: us-east-2
